# See https://docs.docker.com/engine/tutorials/dockerimages/#/building-an-image-from-a-dockerfile
FROM ubuntu:16.04
MAINTAINER keyamb <yasutake.kiyoshi@gmail.com>
RUN apt-get update && apt-get install -y ruby ruby-dev
RUN gem install sinatra
